title: A programmer's blog
email: pascal@pascaldimassimo.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog, where I write mostly about software development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pascaldimassimo
github_username:  pascaldimassimo

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

permalink:        /:year/:month/:day/:title/
