title: A programmer's blog
email: pascal@pascaldimassimo.com
author: Pascal Dimassimo
twitter_username: pascaldimassimo
github_username:  pascaldimassimo

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

permalink:        /:year/:month/:day/:title/
